---
site_name: "Translator Testing Model"
theme:
  name: material
  # palette:
  #  scheme: slate
  #  primary: cyan
  features:
    - content.tabs.link
plugins:
  - search
  - mermaid2
nav:
  # - Home: home.md
  - Index: index.md
  - About: about.md
  - Harmonizer: harmonizer.html
site_url: https://TranslatorSRI.github.io/TranslatorTestingModel
repo_url: https://github.com/TranslatorSRI/TranslatorTestingModel

# Uncomment this block to enable use of Google Analytics.
# Replace the property value with your own ID.
# extra:
#   analytics:
#     provider: google
#     property: G-XXXXXXXXXX
